// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msjvkpmubbrvaxviivvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zanZrcG11YmJydmF4dmlpdnZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMzg0MDAsImV4cCI6MjA2NDgxNDQwMH0.Del-CleH293mKh9dHcK9MldZoHd-CJ71yac8BD5YEIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);